package MyLang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Transition_Constraints extends BaseConstraintsDescriptor {
  public Transition_Constraints() {
    super(CONCEPTS.Transition$vS);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.from$apmO, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:17829034-05e0-42f2-ad4b-fec5dc3c32d1(MyLang.constraints)", "1353375090556920979");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(SNodeOperations.ofConcept(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.StateMachine$tt, true, false), LINKS.elements$avDO), CONCEPTS.State$Xg));
          }
        };
      }
    };
    BaseReferenceConstraintsDescriptor d1 = new BaseReferenceConstraintsDescriptor(LINKS.to$auKb, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:17829034-05e0-42f2-ad4b-fec5dc3c32d1(MyLang.constraints)", "1353375090556922112");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(SNodeOperations.ofConcept(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.StateMachine$tt, true, false), LINKS.elements$avDO), CONCEPTS.State$Xg));
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    references.put(d1.getReference(), d1);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Transition$vS = MetaAdapterFactory.getConcept(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797081e30bL, "MyLang.structure.Transition");
    /*package*/ static final SConcept StateMachine$tt = MetaAdapterFactory.getConcept(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797081e306L, "MyLang.structure.StateMachine");
    /*package*/ static final SConcept State$Xg = MetaAdapterFactory.getConcept(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797080ae8fL, "MyLang.structure.State");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink from$apmO = MetaAdapterFactory.getReferenceLink(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797081e30bL, 0x12c827797081e30cL, "from");
    /*package*/ static final SContainmentLink elements$avDO = MetaAdapterFactory.getContainmentLink(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797081e306L, 0x12c827797081e312L, "elements");
    /*package*/ static final SReferenceLink to$auKb = MetaAdapterFactory.getReferenceLink(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797081e30bL, 0x12c827797081e30eL, "to");
  }
}
