package MyLang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Empty_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new State_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new StateMachine_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Transition_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797085c707L), MetaIdFactory.conceptId(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797080ae8fL), MetaIdFactory.conceptId(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797081e306L), MetaIdFactory.conceptId(0xc840535e42134a05L, 0x832f5cc528f47f6eL, 0x12c827797081e30bL)).seal();
}
